# Generated by Django 3.1.4 on 2021-05-24 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('song', models.FileField(upload_to='song/')),
                ('status', models.CharField(choices=[('Movie', 'Movie'), ('Album', 'Album')], max_length=20)),
                ('format', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video')], max_length=20)),
                ('singers', models.CharField(max_length=100)),
                ('musiccompany', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='song/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subcategory.subcategory')),
            ],
        ),
    ]
